project:
  type: website

website:
  title: "Pesquisa Para Elas 2024"
  sidebar:
    background: purple
    logo: "images/logostem.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/rstudio-conf-2022/teach-ds-course-website
        text: GitHub
      - icon: cloud-fill
        href: https://rstudio.cloud/spaces/237799
        text: RStudio Cloud
    style: docked
    contents:
      - href: index.qmd
        text: PÃ¡gina Inicial
      - href: syllabus.qmd
        text: Recursos
      - href: schedule.qmd
        text: Cronograma
        
format:
  html:
    theme: Materia
    css: styles.css #Reference an external CSS file
toc: true


